# Generated by Django 5.0 on 2024-04-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_projects_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='Zakat donations', max_length=400),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='donations',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
