# Generated by Django 5.0 on 2024-04-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_title_alter_blogpost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
